version: "3.8"
services:
  backend:
    image: "laviniaflorinagavril/movie-renting:2.10.2022.12.8.23"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
