version: "3.8"
services:
  backend:
    image: "laviniaflorinagavril/movie-renting:8.10.2022.10.19.27"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
